name:  trigger-rally-game
title:  Trigger Rally
version: "0.6.5"
summary:   A 3D rally simulation with a great physics engine for drifting, over 100 maps
description: |
  A 3D rally simulation with a great physics engine for drifting, over 100 maps, different terrain materials like dirt, asphalt, sand, ice etc. and various weather, light and fog conditions give this rally simulation the edge over many other free games. You need to make it through the maps in often tight time limits and can further improve by beating the recorded high scores. All attached single races must be finished in time in order to win an event, unlocking additional events and cars. Most maps are equipped with spoken co-driver notes and co-driver icons.

grade: stable
icon: trigger-rally_icon.png

base: core18
confinement: strict

architectures:
  - build-on: amd64
  - build-on: i386

environment:
  WINEDLLOVERRIDES: "$WINEDLLOVERRIDES;mscoree,mshtml="    # Prevent pop-ups about Wine Mono and Wine Gecko
  SOMMELIER_STRICT: "1"                                    # Make Sommelier exit when unset variable is used. (useful to find bugs in sommelier)

apps:
  trigger-rally:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier run-exe
    environment:
      RUN_EXE: "C:/Program Files (x86)/Trigger Rally 0.6.5/bin/trigger-rally.exe"
      INSTALL_EXE: "$SNAP/trigger-rally-0.6.5-win32-setup.exe"
      #INSTALL_FLAGS: "/S"
    plugs:
      - home
      - network
      - network-bind
      - removable-media
      - cups
  # The wine command can be used to run applications inside the wine
  # environment that this snap uses.
  #
  # For example, users can configure the wine environment of this snap
  # by running `myapp.wine winecfg`.
  wine:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier
    plugs:
      - home
      - network
      - network-bind
      - removable-media
      - cups
 # The winetricks command can be used to run winetricks inside the wine
  # environment that this snap uses.
  winetricks:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier winetricks
    plugs:
      - network

parts:
  installer:
    plugin: dump
    source: ./

  # The sommelier script helps you snap Windows applications using Wine. It 
  # initializes and configures Wine and installs the Windows application.
  sommelier:
    plugin: make
    source: https://github.com/snapcrafters/sommelier-core.git

# These plugs are used to connect the snap to the wine runtime.
plugs:
  wine-runtime:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime
  wine-5-stable:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-5-stable

